version: 2

models:
  - name: Athlete
    description: "Table representing detailed athlete information."
    config:
      materialized: table  # Materialize as a table
      contract:
        enforced: true
    columns:
      - name: id
        description: "Unique identifier for the athlete."
        data_type: integer
        tests:
          - unique
          - not_null

      - name: year
        description: "Year of the games the athlete participated in."
        data_type: string
        tests:
          - not_null

      - name: sport_id
        description: "Identifier for the sport the athlete participated in."
        data_type: integer
        tests:
          - not_null

      - name: name
        description: "Name of the athlete."
        data_type: string
        tests:
          - not_null

      - name: sex
        description: "Sex of the athlete."
        data_type: string
        tests:
          - not_null

      - name: age
        description: "Age of the athlete during the event."
        data_type: integer

      - name: height
        description: "Height of the athlete in centimeters."
        data_type: float

      - name: weight
        description: "Weight of the athlete in kilograms."
        data_type: float

      - name: team
        description: "Team the athlete represented."
        data_type: string
        tests:
          - not_null

      - name: noc
        description: "National Olympic Committee code."
        data_type: string
        tests:
          - not_null

      - name: season
        description: "Season of the games (Summer or Winter)."
        data_type: string
        tests:
          - not_null

      - name: city
        description: "City where the games were held."
        data_type: string

      - name: sport
        description: "Sport the athlete participated in."
        data_type: string
        tests:
          - not_null

      - name: event
        description: "Event within the sport."
        data_type: string
        tests:
          - not_null

      - name: medal
        description: "Type of medal won (Gold, Silver, Bronze, or NULL)."
        data_type: string
