version: 2

models:
  - name: noc_region
    description: "Creates a table with the NOC and corresponding region."
    columns:
      - name: noc
        description: "National Olympic Committee (NOC) code."
        tests:
          - not_null
          - unique
      - name: region
        description: "The region corresponding to the NOC code."

tests:
  - name: unique
    description: |
      Ensures that each `noc` is unique in the `noc_region` model.
  - name: not_null
    description: |
      Ensures that `noc` values are not NULL in the `noc_region` model.
