version: 2

models:
  - name: Noc_Region
    description: "Mapping of National Olympic Committee (NOC) codes to regions."
    config:
      contract:
        enforced: true
    columns:
      - name: noc
        description: "National Olympic Committee (NOC) code."
        data_type: string
        constraints:
          - type: primary_key
        tests:
          - unique
          - not_null

      - name: region
        description: "Region corresponding to the NOC code."
        data_type: string
        tests:
          - not_null
