version: 2

models:
  - name: Medal_Type_Record
    description: "A record of Olympic medals won by each country, categorized by type and sport."
    columns:
      - name: name
        description: "The name associated with the record (e.g., country name or athlete)."
        tests:
          - not_null
          - unique

      - name: sport_id
        description: "The unique identifier for each sport."

      - name: noc
        description: "National Olympic Committee (NOC) code representing each country."

      - name: start_year
        description: "The starting year of the Olympic event or period covered."

      - name: end_year
        description: "The ending year of the Olympic event or period covered."

      - name: gold_won
        description: "The number of gold medals won in the specified period."
        tests:
          - not_null

      - name: silver_won
        description: "The number of silver medals won in the specified period."
        tests:
          - not_null

      - name: bronze_won
        description: "The number of bronze medals won in the specified period."
        tests:
          - not_null
